# Generated by Django 3.0.8 on 2020-09-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alllisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alllisting',
            new_name='All_Listings',
        ),
        migrations.RenameField(
            model_name='all_listings',
            old_name='listingid',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='listingid',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='closedbid',
            old_name='listingid',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listingid',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listingid',
            new_name='listing_id',
        ),
    ]
